CREATE TABLE sub (
    "adsh" CHAR(20) NOT NULL,
    "cik" CHAR(10) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "sic" INTEGER(4),
    "countryba" CHAR(2) NOT NULL,
    "stprba" CHAR(2),
    "cityba" VARCHAR NOT NULL,
    "zipba" VARCHAR,
    "bas1" VARCHAR,
    "bas2" VARCHAR,
    "baph" VARCHAR,
    "countryma" CHAR(2),
    "stprma" CHAR(2),
    "cityma" VARCHAR,
    "zipma" VARCHAR(10),
    "mas1" CHAR,
    "mas2" CHAR,
    "countryinc" CHAR(3) NOT NULL,
    "stprinc" CHAR(2),
    "ein" CHAR(10),
    "former" VARCHAR,
    "changed" CHAR(8),
    "afs" CHAR(5),
    "wksi" BOOLEAN NOT NULL,
    "fye" CHAR(4) NOT NULL,
    "form" CHAR(10) NOT NULL,
    "period" CHAR(8) NOT NULL,
    "fy" CHAR(4) NOT NULL,
    "fp" CHAR(2) NOT NULL,
    "filed" CHAR(8) NOT NULL,
    "accepted" DATETIME NOT NULL,
    "prevrpt" BOOLEAN NOT NULL,
    "detail" BOOLEAN NOT NULL,
    "instance" CHAR(32) NOT NULL,
    "nciks" CHAR(4) NOT NULL,
    "aciks" VARCHAR
);
